vich_uploader:
    db_driver: orm

    mappings:
        partner_file:
            uri_prefix: /uploads/images_partner
            upload_destination: '%kernel.project_dir%/public/uploads/images_partner'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true